repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: no-commit-to-branch
        args: [--branch, development, --branch, master]
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: check-json
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
    -   id: name-tests-test
        args: ['--django']
    -   id: requirements-txt-fixer
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.3
    hooks:
    -   id: python-safety-dependencies-check
        stages: [manual]
-   repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
    -   id: bandit
        stages: [manual]
-   repo: https://github.com/twu/skjold
    rev: v0.1.5
    hooks:
    - id: skjold
      name: "skjold: Auditing dependencies for known vulnerabilities."
      entry: skjold audit
      args: [-s, gemnasium, -s, pyup]
      require_serial: true
      language: python
      language_version: python3.7
      files: ^(requirements.*\.txt)$
      stages: [manual]
-   repo: https://github.com/hakancelik96/unimport
    rev: 0.2.7
    hooks:
    - id: unimport
      args: [-r, --include-star-import]
      files: "\\.(py)$"
      exclude: (__init__.py)|mainapp/migrations/.*|.*wsgi.py$
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
        exclude: ^mainapp/migrations/
        language_version: python3.7
-   repo: local
    hooks:
    -   id: tests
        name: tests
        entry: ./manage.py test
        language: system
        pass_filenames: false
        stages: [push]
