# Generated by Django 2.2.1 on 2019-07-25 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('action', models.CharField(blank=True, max_length=1024, null=True)),
                ('note', models.CharField(blank=True, max_length=2048, null=True)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activities', to='mainapp.Dataset')),
                ('study', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activities', to='mainapp.Study')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activities',
                'unique_together': {('ts', 'user')},
            },
        ),
    ]
