# Generated by Django 2.2.1 on 2019-07-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_activity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=set(),
        ),
    ]
