# Generated by Django 2.2.1 on 2019-05-26 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190522_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execution',
            name='study',
        ),
        migrations.AddField(
            model_name='study',
            name='execution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='studies', to='mainapp.Execution'),
        ),
    ]
