# Generated by Django 2.2.1 on 2019-07-26 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190726_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='execution_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='the_execution', to=settings.AUTH_USER_MODEL),
        ),
    ]
