# Generated by Django 2.2.1 on 2019-06-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20190612_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='tags', to='mainapp.Tag'),
        ),
    ]
