# Generated by Django 2.2.1 on 2019-07-28 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20190726_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('note', models.CharField(blank=True, max_length=2048, null=True)),
                ('permission', models.CharField(blank=True, max_length=32, null=True)),
                ('state', models.CharField(blank=True, max_length=32, null=True)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='requests', to='mainapp.Dataset')),
                ('study', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='requests', to='mainapp.Study')),
                ('user_requested', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'requests',
            },
        ),
    ]
