# Generated by Django 2.2.1 on 2019-07-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='users_requested_aggregated_access',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='users_requested_full_access',
        ),
        migrations.AlterField(
            model_name='request',
            name='state',
            field=models.CharField(blank=True, default='pending', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('dataset_access', 'dataset_access')], default='dataset_access', max_length=32),
            preserve_default=False,
        ),
    ]
