# Generated by Django 2.2.1 on 2019-06-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20190612_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='override_bucket',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='mainapp.Tag'),
        ),
    ]
