# Generated by Django 2.2.1 on 2019-06-20 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_dataset_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='status',
            new_name='state',
        ),
    ]
