# Generated by Django 2.2.1 on 2019-07-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20190729_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='programmatic_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
