# Generated by Django 2.2.1 on 2019-06-26 12:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20190626_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='users',
            field=models.ManyToManyField(related_name='datasets', to=settings.AUTH_USER_MODEL),
        ),
    ]
