# Generated by Django 2.2.1 on 2019-08-04 13:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20190804_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
