# Generated by Django 2.2.1 on 2019-08-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_activity_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='action',
        ),
    ]
