# Generated by Django 2.2.1 on 2019-06-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20190626_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_execution',
            field=models.BooleanField(default=False),
        ),
    ]
