# Generated by Django 2.2.1 on 2019-06-27 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_user_is_execution'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='study',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='study',
            name='organization',
        ),
    ]
