# Generated by Django 2.2.1 on 2019-07-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20190627_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='tags',
            field=models.ManyToManyField(related_name='study_tags', to='mainapp.Tag'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='tags',
            field=models.ManyToManyField(related_name='dataset_tags', to='mainapp.Tag'),
        ),
    ]
