# Generated by Django 2.2.1 on 2019-08-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20190827_1135'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'category')},
        ),
    ]
