# Generated by Django 2.2.1 on 2019-09-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20190827_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
