# Generated by Django 2.2.1 on 2019-07-08 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20190708_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='override_bucket',
            new_name='bucket',
        ),
    ]
