# Generated by Django 2.2.1 on 2019-09-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='cover',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='cover',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
