# Generated by Django 2.2.1 on 2019-07-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20190708_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
