# Generated by Django 2.2.1 on 2019-07-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20190709_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='glue_database',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='s3_object',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='state',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
