# Generated by Django 2.2.1 on 2019-11-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_organization_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='glue_table',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
