# Generated by Django 2.2.1 on 2019-07-16 08:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20190711_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='s3_object',
        ),
        migrations.AddField(
            model_name='datasource',
            name='s3_objects',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
