# Generated by Django 2.2.1 on 2019-11-13 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_dataset_ancestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='ancestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='mainapp.Dataset'),
        ),
    ]
