# Generated by Django 2.2.1 on 2019-07-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20190716_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='dir',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
