# Generated by Django 2.2.1 on 2019-07-23 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_datasource_dir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='users',
        ),
        migrations.AddField(
            model_name='dataset',
            name='admin_users',
            field=models.ManyToManyField(related_name='admin_datasets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataset',
            name='aggregated_users',
            field=models.ManyToManyField(related_name='aggregated_datasets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataset',
            name='default_user_permission',
            field=models.CharField(blank=True, choices=[('none', 'none'), ('aggregated', 'aggregated')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='full_access_users',
            field=models.ManyToManyField(related_name='full_access_datasets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataset',
            name='users_requested_full_access',
            field=models.ManyToManyField(related_name='requested_full_access_for_datasets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='state',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private'), ('archived', 'archived')], default='private', max_length=32),
            preserve_default=False,
        ),
    ]
