# Generated by Django 2.2.1 on 2019-12-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20191113_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='glue_database',
            new_name='glue_database_override',
        ),
    ]
