# Generated by Django 2.2.1 on 2019-07-24 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20190723_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='users_requested_aggregated_access',
            field=models.ManyToManyField(related_name='requested_aggregated_access_for_datasets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='default_user_permission',
            field=models.CharField(choices=[('none', 'none'), ('aggregated', 'aggregated')], max_length=32, null=True),
        ),
    ]
