# Generated by Django 2.2.1 on 2019-12-12 14:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_dataset_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='preview',
        ),
        migrations.AddField(
            model_name='datasource',
            name='ancestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='mainapp.DataSource'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='cohort',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
