# Generated by Django 2.2.1 on 2020-01-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_documentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='is_discoverable',
            field=models.BooleanField(default=True),
        ),
    ]
