# Generated by Django 2.2.1 on 2020-02-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_hiddenDataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='is_discoverable',
            field=models.BooleanField(),
        ),
    ]
