# Generated by Django 2.2.1 on 2020-03-13 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_hiddenDataset_updateField'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.CreateModel(
                name='StudyDataset',
                fields=[
                    ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Dataset')),
                ],
                options={
                    'db_table': 'studies_datasets',
                },
            ),
            migrations.AlterField(
                model_name='study',
                name='datasets',
                field=models.ManyToManyField(related_name='studies', through='mainapp.StudyDataset',
                                             to='mainapp.Dataset'),
            ),
            migrations.AddField(
                model_name='studydataset',
                name='study',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Study'),
            ),
            migrations.AlterUniqueTogether(
                name='studydataset',
                unique_together={('dataset', 'study')},
            ),
        ])
    ]
