# Generated by Django 2.2.1 on 2020-03-13 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_studyDatasets'),
    ]

    operations = [
        migrations.AddField(
            model_name='studydataset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studydataset',
            name='permission',
            field=models.CharField(choices=[('full_access', 'full_access'), ('aggregated_access', 'aggregated_access')], default='full_access', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studydataset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
