# Generated by Django 2.2.1 on 2020-05-16 12:59

import django.db.models.deletion
from django.db import migrations, models


def set_organization(apps, schema_editor):
    studies = apps.get_model("mainapp", "Study")
    organizations = apps.get_model("mainapp", "Organization")
    default_organization = organizations.objects.get_or_create(default=True)
    if not default_organization:
        print("No default organization found")
    for study in studies.objects.all():
        if not study.organization:
            first_dataset = study.datasets.first()
            # in case of study without dataset - set the organization to the default (lynx)
            if not first_dataset:
                study.organization = default_organization
            else:
                study.organization = first_dataset.organization
            study.save(update_fields=['organization'])


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0031_add_id_to_studydataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='studies',
                to='mainapp.Organization',
                null=True,
                blank=True
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_organization, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='study',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='studies',
                to='mainapp.Organization'
            ),
            preserve_default=False,
        ),
    ]
