# Generated by Django 2.2.1 on 2020-05-17 11:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_study_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(choices=[('can_copy_paste_in_notebook', 'can_copy_paste_in_notebook')], max_length=32)),
                ('value', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='preferences', to='mainapp.Organization')),
            ],
            options={
                'db_table': 'organizations_preferences',
                'unique_together': {('organization', 'key')},
            },
        ),
    ]
