# Generated by Django 2.2.1 on 2020-07-08 23:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_organizationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='studydataset',
            name='permission_attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studydataset',
            name='permission',
            field=models.CharField(choices=[('full_access', 'full_access'), ('limited', 'limited'), ('deid', 'deid'), ('synthetic', 'synthetic'), ('aggregated_access', 'aggregated_access')], max_length=32),
        ),
    ]
