# Generated by Django 2.2.1 on 2020-07-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_auto_20200708_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='status',
            field=models.CharField(choices=[('creating', 'creating'), ('starting', 'starting'), ('active', 'active'), ('stopping', 'stopping'), ('stopped', 'stopped'), ('error', 'error'), ('deleted', 'deleted')], default='active', max_length=32),
        ),
    ]
