# Generated by Django 2.2.1 on 2020-07-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_study_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='glue_table',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
