# Generated by Django 2.2.1 on 2020-07-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_datasource_glue_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='glue_table',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studydataset',
            name='permission',
            field=models.CharField(choices=[('full_access', 'full_access'), ('limited_access', 'limited_access'), ('deid_access', 'deid_access'), ('synthetic_access', 'synthetic_access'), ('aggregated_access', 'aggregated_access')], max_length=32),
        ),
    ]
