# Generated by Django 2.2.1 on 2020-07-27 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_starred_datasets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='starred_dataset',
        ),
        migrations.AddField(
            model_name='dataset',
            name='starred_users',
            field=models.ManyToManyField(related_name='starred_datasets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='StarredDataset',
        ),
    ]
