# Generated by Django 2.2.1 on 2020-08-12 10:29

import django.utils.timezone
from django.db import migrations, models


def set_created_at_from_updated_at(apps, schema_editor):
    Study = apps.get_model('mainapp', 'Study')
    for study in Study.objects.all().iterator():
        study.created_at = study.updated_at
        study.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_dataset_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(set_created_at_from_updated_at, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='study',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
