# Generated by Django 2.2.1 on 2020-08-15 16:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0043_datasets_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='permission_attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
    ]
