# Generated by Django 2.2.1 on 2020-10-01 09:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid

from mainapp.utils.data_source import generate_columns


def update_data_source_columns(apps, schema_editor):
    data_sources = apps.get_model("mainapp", "DataSource")
    for data_source in data_sources.objects.all().iterator():
        if data_source.glue_table:
            try:
                generate_columns(data_source)
            except Exception as e:
                print(f"An error occurred when trying to extract columns for Data Source {data_source.id}\nerror - {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_user_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='columns',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(update_data_source_columns, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='dataset',
            name='default_user_permission',
            field=models.CharField(choices=[('none', 'none'), ('aggregated_access', 'aggregated_access'), ('limited_access', 'limited_access'), ('deid_access', 'deid_access')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='datasetuser',
            name='permission',
            field=models.CharField(choices=[('limited_access', 'limited_access'), ('deid_access', 'deid_access')], max_length=32),
        ),
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('dataset_access', 'dataset_access'), ('deid_access', 'deid_access')], max_length=32),
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('salt_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('group_age_over', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='mainapp.Dataset')),
            ],
            options={
                'db_table': 'methods',
                'unique_together': {('dataset', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DataSourceMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included', models.BooleanField(default=True)),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('state', models.CharField(blank=True, default='pending', max_length=32)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='mainapp.DataSource')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_source_methods', to='mainapp.Method')),
            ],
            options={
                'db_table': 'data_source_methods',
                'unique_together': {('method', 'data_source')},
            },
        ),
    ]
