# Generated by Django 2.2.1 on 2020-11-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0047_machinetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='bucket_override',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='glue_database_override',
        ),
    ]
