# Generated by Django 2.2.1 on 2020-10-01 09:03

from django.db import migrations


def update_s3_objects(apps, schema_editor):
    data_sources = apps.get_model("mainapp", "DataSource")
    for data_source in data_sources.objects.all().iterator():
        s3_objects = data_source.s3_objects
        for s3_obj in s3_objects:
            path_parts = s3_obj["key"].split("/")
            if path_parts and path_parts[0] != data_source.dataset.programmatic_name:
                path_parts.insert(0, data_source.dataset.programmatic_name)
            s3_obj["key"] = "/".join(path_parts)
        data_source.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0048_auto_20201105_1035'),
    ]

    operations = [
        migrations.RunPython(update_s3_objects, reverse_code=migrations.RunPython.noop),
    ]
